on: [ pull_request ]
name: Check
jobs:
  util:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Format Check
        run: |
          cargo fmt --all -- --check
      - name: Build Check
        run: |
          cargo check
      - name: Test
        run: |
          cargo test --all-features
